### ISSUE TITLE
Error: Could not find or load main class org.acoli.conll.rdf.CoNLLStreamExtractor

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [acoli-repo/conll-rdf#18]
Hello, In the working directory of  `conll-rdf/CoNLL-RDF/examples/` ,  I run:
 `gunzip -c ../data/ud/UD_English-master/en-ud-dev.conllu.gz > en-ud-dev.conllu`  

and I encountered a bug When I was executing the following command:

`cat en-ud-dev.conllu | ../run.sh CoNLLStreamExtractor \
https://github.com/UniversalDependencies/UD_English# ID WORD LEMMA UPOS POS FEAT HEAD EDGE DEPS MISC `  

**Returned the following bug:**
`Error: Could not find or load main class org.acoli.conll.rdf.CoNLLStreamExtractor
`

ps：The **CoNLLStreamExtractor.java**  is located in the "conll-rdf/CoNLL-RDF/src/org/acoli/conll/rdf/CoNLLStreamExtractor.java" working directory.

**Comment by cfaeth** [comment]
Hello, great to see you are interested in CoNLL-RDF. 

The error message you encounter means, that your Java installation was unable to find the compiled CoNLL-RDF classes in your folder structure. This may have a lot of reasons and I am unable to recreate your problem on my machine even when using exactly the folder structure and commands you provided.

Please try the following and provide us with more detailed information:
- which OS are you using? (e.g. Windows+Cygwin, Ubuntu etc.)
- which Java version? JRE or JDK? Oracle or OpenJDK? (plain JRE will not work, since it lacks a compiler; Oracle JDK 8 is recommended.)
- have your CoNLL-RDF classes been successfully compiled to `conll-rdf/CoNLL-RDF/bin/org/acoli/conll/rdf/` ? If not, please try to run `compile.sh` independently.
- please echo the actual commands executed by your `run.sh`, so you can see the classpath it provides to the Java runtime. To do so, just add "-x" to the first line of run.sh: `#!/bin/bash -x` and try to execute it again. Please check whether the classpath fits your actual folder structure.
- if your absolute path contains hanzi or other special characters this might also be causing problems depending on your Java version (just guessing).
- if none of this helps, please send us the full "-x" log of the `run.sh` and `compile.sh`.

Best wishes and good luck!

**Comment by xiaoxiaoAurora** [comment]
> * Ubuntu


Thank you very much .After compile.sh is executed, I run it successfully.
