### ISSUE TITLE
Updater must not rely on @prefix for splitting

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#32]
Currently, the the CoNLLRDFUpdater is *NOT* able to split the output of CoNLLBrackets2RDF.
Apparently, the splitting criterion is whether it encounter @prefix in its input Turtle.

HOWEVER, the @prefix notation is permitted along with the PREFIX notation, and CoNLLBrackets2RDF uses the latter, so the Updater will process all input as a single chunk of data.

Note that this is a more general issue and that more transparent requirements for splitting the input are required.

**Comment by leogott** [comment]
I'll address this issue once I'm done with my current assignment.

**Comment by leogott** [comment]
Problem: There are a lot more places in the conll-rdf codebase, where some form of splitting happens when a new block of comments and/or prefixes is encountered, than I expected.
I can basically search for `startsWith("@` and modify all occurences to also work for `"PREFIX"`, but I cannot predict what possible side effects this change would have.

Should I go ahead anyway?

https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFFormatter.java#L407-L408
https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFFormatter.java#L767
https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFFormatter.java#L803

https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdater.java#L870-L877
https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdater.java#L933
https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdater.java#L1027

https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFAnnotator.java#L57
https://github.com/acoli-repo/conll-rdf/blob/0fdd35a0a8ac082b0863dad0c37cb343d6810181/src/main/java/org/acoli/conll/rdf/CoNLLRDFAnnotator.java#L102

**Comment by cfaeth** [comment]
Most classes contain the line parsing inside a while block and after the stream has closed. Please consolidate the two blocks as discussed.

Adding a startsWith("PREFIX) for all classes reading RDF should not have any negative side effects, since PREFIX is a valid operator. Should any of the operators be contained as a first character after line-break inside a multi-line String the current implementiation could break anyway, but this should be extremely uncommon.
