### ISSUE TITLE
LLOD RDF Format

### ISSUE THREAD

**Issue by avramandrei** [acoli-repo/conll-rdf#38]
Hello,

I am trying to convert a CoNLL-U file to RDF format as presented in LLOD TreeBanks (e.g. [link to French example](https://datahub.ckan.io/dataset/95a607ea-1409-44c7-acdc-696a195c84fd/resource/8f9c0b59-7a9f-4af5-9ce4-bbb50e104c0a/download/udfrench.rdf) ) and I have seen that they used this tool for conversion. However, I don't see how I can convert it in that specific format. I have tried all formats of CoNLLRDFFormatter and none of them are what I am looking for. Could you help me out?

Thank you,
Andrei

**Comment by chiarcos** [comment]
Apparently you're looking for RDF-XML. CoNLL-RDF produces Turtle, another  
standard RDF serialization that is normally considered easier to consume  
and interpret that RDF-XML. But you can convert Turtle to RDF-XML using  
off-the-shelf tools, e.g., the command-line tool Raptor  
(http://librdf.org/raptor/rapper.html) or Apache Jena (shipped with  
CoNLL-RDF, https://jena.apache.org/documentation/io/).

Does that help?

Am .09.2020, 09:11 Uhr, schrieb Andrei-Marius Avram  
<notifications@github.com>:

**Comment by cfaeth** [comment]
Hi Andrei,

I could not quite pinpoint the exact source of your problem, so I provide two answers:

short answer:

If you want a basic conversion for CoNLL-U, you can directly employ the following example script: [https://github.com/acoli-repo/conll-rdf/blob/master/examples/convert-ud.sh](https://github.com/acoli-repo/conll-rdf/blob/master/examples/convert-ud.sh)
It is included in the tutorial here: [https://github.com/acoli-repo/conll-rdf/tree/master/examples#i-converting-conll-to-conll-rdf-and-back](https://github.com/acoli-repo/conll-rdf/tree/master/examples#i-converting-conll-to-conll-rdf-and-back)

This will give you Turtle data, which is a standard W3C serialization for RDF. The example data on datahub had to be uploaded in RDF/XML to be counted as Linked Data. We however usually encourage Turtle for CoNLL-RDF. In the end it is just two serializations of the same graph. I believe I just used Apache Jena to convert from Turtle to RDF/XML but you can also resort to other  standard tools, e.g.: [https://www.w3.org/wiki/ConverterFromRdf](https://www.w3.org/wiki/ConverterFromRdf)

long answer:

In order to convert CoNLL-U data to CoNLL-RDF, you need to employ the CoNLLStreamExtractor class and supply it with a base URI (to be used for identifying the tokens and sentences). If you plan on hosting the data, it is recommended to use the URL on which the resulting data can be accessed later on. 

You further need to specify the column names, which will be mapped as RDF properties. For CoNLL-U, these are the reference descriptions:
CoNLL-U v2: [https://github.com/acoli-repo/conll-rdf/blob/master/examples/convert-ud.sh](https://universaldependencies.org/format.html)
CoNLL-U v1: [https://github.com/acoli-repo/conll-rdf/blob/master/examples/convert-ud.sh](https://universaldependencies.org/docs/format.html)
However, for dependency relations in CoNLL-RDF, we usually name the columns HEAD and EDGE (instead of HEAD and DEPREL). Using this naming convention, most of our additional SPARQL scripts may work for your data out-of-the-box, if needed.

The CoNLLRDFFormatter can be used to convert the output of the StreamExtractor to the CoNLL-RDF canonical format - a Turtle-based format, which uses a single line per token and its respective properties, thus resembling the original CoNLL-TSV.
The formatter can also be used for transforming back to CoNLL-U or other TSV formats.

All these steps are performed in the example above. You only need to adjust the part `# 1. read` to read from your input data.


I hope this helps! Best wishes,

Christian

**Comment by avramandrei** [comment]
Hi,

Thank you very much for your answers! I am also sorry for any confusion that I may have caused, I didn't know that these two are serializations of the same graph, and that is easy to convert between them.

I managed to convert the resulted .ttl (Turtle) file into RDF/XML using the Raptor tool.

Bests
Andrei

**Comment by cfaeth** [comment]
Glad we could help!
